version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    open-pull-requests-limit: 3
    assignees: [wini83]
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      non-major:
        update-types: [minor, patch]
  # Python uv
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    open-pull-requests-limit: 3
    assignees: [wini83]
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      non-major:
        update-types: [minor, patch]
  # bun
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    open-pull-requests-limit: 3
    assignees: [wini83]
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      non-major:
        update-types: [minor, patch]
    ignore:
      - dependency-name: "@hey-api/openapi-ts"
  # Docker
  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
    schedule:
      interval: weekly
    target-branch: dev
    open-pull-requests-limit: 3
    assignees: [wini83]
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      non-major:
        update-types: [minor, patch]
  # Docker Compose
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    open-pull-requests-limit: 3
    assignees: [wini83]
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      non-major:
        update-types: [minor, patch]
