// This file is auto-generated by @hey-api/openapi-ts

export const BillingPeriodInputSchema = {
    properties: {
        year: {
            type: 'integer',
            maximum: 9999,
            minimum: 1,
            title: 'Year'
        },
        month: {
            type: 'integer',
            maximum: 12,
            minimum: 1,
            title: 'Month'
        }
    },
    type: 'object',
    required: ['year', 'month'],
    title: 'BillingPeriodInput'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesPublic'
} as const;

export const CategoryCreateSchema = {
    properties: {
        category_group_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Group Id'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        code: {
            type: 'string',
            maxLength: 4,
            minLength: 4,
            pattern: '^[A-Z]{4}$',
            title: 'Code'
        },
        data_source_policy: {
            '$ref': '#/components/schemas/DataSourcePolicy',
            default: 'hybrid'
        },
        recurrence_interval: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recurrence Interval'
        },
        recurrence_unit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RecurrenceUnit'
                },
                {
                    type: 'null'
                }
            ]
        },
        recurrence_anchor: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recurrence Anchor'
        },
        currency: {
            '$ref': '#/components/schemas/Currency',
            default: 'PLN'
        },
        due_day: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 31,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Day'
        }
    },
    type: 'object',
    required: ['category_group_id', 'name', 'code'],
    title: 'CategoryCreate'
} as const;

export const CategoryGroupCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryGroupCreate'
} as const;

export const CategoryGroupPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        }
    },
    type: 'object',
    required: ['id', 'ledger_id', 'name', 'description', 'is_active', 'archived_at'],
    title: 'CategoryGroupPublic'
} as const;

export const CategoryGroupUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryGroupUpdate'
} as const;

export const CategoryGroupsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryGroupPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoryGroupsPublic'
} as const;

export const CategoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        category_group_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Group Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        data_source_policy: {
            '$ref': '#/components/schemas/DataSourcePolicy'
        },
        recurrence_interval: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recurrence Interval'
        },
        recurrence_unit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RecurrenceUnit'
                },
                {
                    type: 'null'
                }
            ]
        },
        recurrence_anchor: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recurrence Anchor'
        },
        currency: {
            '$ref': '#/components/schemas/Currency'
        },
        due_day: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Day'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        }
    },
    type: 'object',
    required: ['id', 'ledger_id', 'category_group_id', 'name', 'description', 'is_active', 'code', 'data_source_policy', 'recurrence_interval', 'recurrence_unit', 'recurrence_anchor', 'currency', 'due_day', 'archived_at'],
    title: 'CategoryPublic'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        data_source_policy: {
            '$ref': '#/components/schemas/DataSourcePolicy'
        },
        recurrence_interval: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recurrence Interval'
        },
        recurrence_unit: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RecurrenceUnit'
                },
                {
                    type: 'null'
                }
            ]
        },
        recurrence_anchor: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recurrence Anchor'
        },
        currency: {
            '$ref': '#/components/schemas/Currency',
            default: 'PLN'
        },
        due_day: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 31,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Day'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['name', 'data_source_policy'],
    title: 'CategoryUpdate'
} as const;

export const CurrencySchema = {
    type: 'string',
    enum: ['PLN', 'EUR', 'USD', 'GBP', 'CHF'],
    title: 'Currency'
} as const;

export const CurrentValueSourceSchema = {
    type: 'string',
    enum: ['unknown', 'automatic', 'manual'],
    title: 'CurrentValueSource'
} as const;

export const DataSourcePolicySchema = {
    type: 'string',
    enum: ['manual', 'automatic', 'hybrid'],
    title: 'DataSourcePolicy'
} as const;

export const EffectiveValueSourceModeSchema = {
    type: 'string',
    enum: ['unknown', 'automatic', 'manual', 'mixed'],
    title: 'EffectiveValueSourceMode'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LedgerAccessRoleSchema = {
    type: 'string',
    enum: ['owner', 'editor', 'viewer'],
    title: 'LedgerAccessRole'
} as const;

export const LedgerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'LedgerCreate'
} as const;

export const LedgerMemberPublicSchema = {
    properties: {
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/LedgerAccessRole'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['ledger_id', 'user_id', 'email', 'full_name', 'role', 'created_at'],
    title: 'LedgerMemberPublic'
} as const;

export const LedgerMemberUpdateSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/LedgerAccessRole'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'LedgerMemberUpdate'
} as const;

export const LedgerMembersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LedgerMemberPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LedgerMembersPublic'
} as const;

export const LedgerPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner User Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'owner_user_id', 'name', 'description', 'created_at', 'updated_at'],
    title: 'LedgerPublic'
} as const;

export const LedgerShareSchema = {
    properties: {
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        role: {
            '$ref': '#/components/schemas/LedgerAccessRole'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'LedgerShare'
} as const;

export const LedgerUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'LedgerUpdate'
} as const;

export const LedgersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LedgerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LedgersPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const ObligationCreateSchema = {
    properties: {
        category_code: {
            type: 'string',
            pattern: '^[A-Z]{4}$',
            title: 'Category Code'
        },
        period: {
            '$ref': '#/components/schemas/BillingPeriodInput'
        },
        data_ready: {
            type: 'boolean',
            title: 'Data Ready',
            default: false
        },
        current_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Amount'
        },
        issue_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Issue Date'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        }
    },
    type: 'object',
    required: ['category_code', 'period'],
    title: 'ObligationCreate'
} as const;

export const ObligationLifecycleSchema = {
    type: 'string',
    enum: ['draft', 'collecting_data', 'ready', 'paid', 'canceled', 'error'],
    title: 'ObligationLifecycle'
} as const;

export const ObligationPeriodPublicSchema = {
    properties: {
        year: {
            type: 'integer',
            maximum: 9999,
            minimum: 1,
            title: 'Year'
        },
        month: {
            type: 'integer',
            maximum: 12,
            minimum: 1,
            title: 'Month'
        }
    },
    type: 'object',
    required: ['year', 'month'],
    title: 'ObligationPeriodPublic'
} as const;

export const ObligationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ledger_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ledger Id'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        category_code: {
            type: 'string',
            title: 'Category Code'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        lifecycle: {
            '$ref': '#/components/schemas/ObligationLifecycle'
        },
        period: {
            '$ref': '#/components/schemas/ObligationPeriodPublic'
        },
        effective_value_source: {
            '$ref': '#/components/schemas/EffectiveValueSourceMode'
        },
        current_amount: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Amount'
        },
        amount_state: {
            '$ref': '#/components/schemas/ValueState'
        },
        amount_source: {
            '$ref': '#/components/schemas/CurrentValueSource'
        },
        issue_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Issue Date'
        },
        issue_date_state: {
            '$ref': '#/components/schemas/ValueState'
        },
        issue_date_source: {
            '$ref': '#/components/schemas/CurrentValueSource'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        due_date_state: {
            '$ref': '#/components/schemas/ValueState'
        },
        due_date_source: {
            '$ref': '#/components/schemas/CurrentValueSource'
        },
        currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'ledger_id', 'category_id', 'category_code', 'key', 'name', 'notes', 'lifecycle', 'period', 'effective_value_source', 'current_amount', 'amount_state', 'amount_source', 'issue_date', 'issue_date_state', 'issue_date_source', 'due_date', 'due_date_state', 'due_date_source', 'currency', 'created_at', 'updated_at'],
    title: 'ObligationPublic'
} as const;

export const ObligationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ObligationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ObligationsPublic'
} as const;

export const RecurrenceUnitSchema = {
    type: 'string',
    enum: ['month', 'year'],
    title: 'RecurrenceUnit'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id', 'created_at'],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const ValueStateSchema = {
    type: 'string',
    enum: ['unknown', 'estimated', 'confirmed', 'overridden'],
    title: 'ValueState'
} as const;