// This file is auto-generated by @hey-api/openapi-ts

export type BillingPeriodInput = {
    year: number;
    month: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategoryCreate = {
    category_group_id: string;
    name: string;
    description?: (string | null);
    code: string;
    data_source_policy?: DataSourcePolicy;
    recurrence_interval?: (number | null);
    recurrence_unit?: (RecurrenceUnit | null);
    recurrence_anchor?: (string | null);
    currency?: Currency;
    due_day?: (number | null);
};

export type CategoryGroupCreate = {
    name: string;
    description?: (string | null);
};

export type CategoryGroupPublic = {
    id: string;
    ledger_id: string;
    name: string;
    description: (string | null);
    is_active: boolean;
    archived_at: (string | null);
};

export type CategoryGroupsPublic = {
    data: Array<CategoryGroupPublic>;
    count: number;
};

export type CategoryGroupUpdate = {
    name: string;
    description?: (string | null);
};

export type CategoryPublic = {
    id: string;
    ledger_id: string;
    category_group_id: string;
    name: string;
    description: (string | null);
    is_active: boolean;
    code: string;
    data_source_policy: DataSourcePolicy;
    recurrence_interval: (number | null);
    recurrence_unit: (RecurrenceUnit | null);
    recurrence_anchor: (string | null);
    currency: Currency;
    due_day: (number | null);
    archived_at: (string | null);
};

export type CategoryUpdate = {
    name: string;
    description?: (string | null);
    data_source_policy: DataSourcePolicy;
    recurrence_interval?: (number | null);
    recurrence_unit?: (RecurrenceUnit | null);
    recurrence_anchor?: (string | null);
    currency?: Currency;
    due_day?: (number | null);
};

export type Currency = 'PLN' | 'EUR' | 'USD' | 'GBP' | 'CHF';

export type CurrentValueSource = 'unknown' | 'automatic' | 'manual';

export type DataSourcePolicy = 'manual' | 'automatic' | 'hybrid';

export type EffectiveValueSourceMode = 'unknown' | 'automatic' | 'manual' | 'mixed';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LedgerAccessRole = 'owner' | 'editor' | 'viewer';

export type LedgerCreate = {
    name: string;
    description?: (string | null);
};

export type LedgerMemberPublic = {
    ledger_id: string;
    user_id: string;
    email: string;
    full_name: (string | null);
    role: LedgerAccessRole;
    created_at: string;
};

export type LedgerMembersPublic = {
    data: Array<LedgerMemberPublic>;
    count: number;
};

export type LedgerMemberUpdate = {
    role: LedgerAccessRole;
};

export type LedgerPublic = {
    id: string;
    owner_user_id: string;
    name: string;
    description: (string | null);
    created_at: string;
    updated_at: string;
};

export type LedgerShare = {
    user_id?: (string | null);
    email?: (string | null);
    role: LedgerAccessRole;
};

export type LedgersPublic = {
    data: Array<LedgerPublic>;
    count: number;
};

export type LedgerUpdate = {
    name: string;
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type ObligationCreate = {
    category_code: string;
    period: BillingPeriodInput;
    data_ready?: boolean;
    current_amount?: (number | string | null);
    issue_date?: (string | null);
    due_date?: (string | null);
    notes?: (string | null);
};

export type ObligationLifecycle = 'draft' | 'collecting_data' | 'ready' | 'paid' | 'canceled' | 'error';

export type ObligationPeriodPublic = {
    year: number;
    month: number;
};

export type ObligationPublic = {
    id: string;
    ledger_id: string;
    category_id: string;
    category_code: string;
    key: string;
    name: string;
    notes: (string | null);
    lifecycle: ObligationLifecycle;
    period: ObligationPeriodPublic;
    effective_value_source: EffectiveValueSourceMode;
    current_amount: (string | null);
    amount_state: ValueState;
    amount_source: CurrentValueSource;
    issue_date: (string | null);
    issue_date_state: ValueState;
    issue_date_source: CurrentValueSource;
    due_date: (string | null);
    due_date_state: ValueState;
    due_date_source: CurrentValueSource;
    currency: (string | null);
    created_at: string;
    updated_at: string;
};

export type ObligationsPublic = {
    data: Array<ObligationPublic>;
    count: number;
};

export type RecurrenceUnit = 'month' | 'year';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ValueState = 'unknown' | 'estimated' | 'confirmed' | 'overridden';

export type CategoriesReadCategoriesData = {
    categoryGroupId?: (string | null);
    includeArchived?: boolean;
    ledgerId: string;
};

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    ledgerId: string;
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryGroupsData = {
    includeArchived?: boolean;
    ledgerId: string;
};

export type CategoriesReadCategoryGroupsResponse = (CategoryGroupsPublic);

export type CategoriesCreateCategoryGroupData = {
    ledgerId: string;
    requestBody: CategoryGroupCreate;
};

export type CategoriesCreateCategoryGroupResponse = (CategoryGroupPublic);

export type CategoriesUpdateCategoryGroupData = {
    categoryGroupId: string;
    ledgerId: string;
    requestBody: CategoryGroupUpdate;
};

export type CategoriesUpdateCategoryGroupResponse = (CategoryGroupPublic);

export type CategoriesArchiveCategoryGroupData = {
    categoryGroupId: string;
    ledgerId: string;
};

export type CategoriesArchiveCategoryGroupResponse = (CategoryGroupPublic);

export type CategoriesUpdateCategoryData = {
    categoryId: string;
    ledgerId: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesArchiveCategoryData = {
    categoryId: string;
    ledgerId: string;
};

export type CategoriesArchiveCategoryResponse = (CategoryPublic);

export type LedgersReadLedgersResponse = (LedgersPublic);

export type LedgersCreateLedgerData = {
    requestBody: LedgerCreate;
};

export type LedgersCreateLedgerResponse = (LedgerPublic);

export type LedgersReadLedgerData = {
    ledgerId: string;
};

export type LedgersReadLedgerResponse = (LedgerPublic);

export type LedgersUpdateLedgerData = {
    ledgerId: string;
    requestBody: LedgerUpdate;
};

export type LedgersUpdateLedgerResponse = (LedgerPublic);

export type LedgersReadLedgerMembersData = {
    ledgerId: string;
};

export type LedgersReadLedgerMembersResponse = (LedgerMembersPublic);

export type LedgersShareLedgerData = {
    ledgerId: string;
    requestBody: LedgerShare;
};

export type LedgersShareLedgerResponse = (LedgerMemberPublic);

export type LedgersDeleteAllCategoriesData = {
    ledgerId: string;
};

export type LedgersDeleteAllCategoriesResponse = (Message);

export type LedgersUpdateLedgerMemberData = {
    ledgerId: string;
    requestBody: LedgerMemberUpdate;
    userId: string;
};

export type LedgersUpdateLedgerMemberResponse = (LedgerMemberPublic);

export type LedgersRemoveLedgerMemberData = {
    ledgerId: string;
    userId: string;
};

export type LedgersRemoveLedgerMemberResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ObligationsReadObligationsData = {
    categoryCode?: (string | null);
    ledgerId: string;
    lifecycle?: (ObligationLifecycle | null);
    month?: (number | null);
    year?: (number | null);
};

export type ObligationsReadObligationsResponse = (ObligationsPublic);

export type ObligationsCreateObligationData = {
    ledgerId: string;
    requestBody: ObligationCreate;
};

export type ObligationsCreateObligationResponse = (ObligationPublic);

export type ObligationsReadObligationData = {
    ledgerId: string;
    obligationKey: string;
};

export type ObligationsReadObligationResponse = (ObligationPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);