// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategoryCreate = {
    category_group_id: string;
    name: string;
    description?: (string | null);
    code?: (string | null);
    creation_policy?: ObligationCreationPolicy;
    period_generation_policy?: PeriodGenerationPolicy;
    currency?: (string | null);
    due_day?: (number | null);
};

export type CategoryGroupCreate = {
    name: string;
    description?: (string | null);
};

export type CategoryGroupPublic = {
    id: string;
    ledger_id: string;
    name: string;
    description: (string | null);
    is_active: boolean;
    archived_at: (string | null);
};

export type CategoryGroupsPublic = {
    data: Array<CategoryGroupPublic>;
    count: number;
};

export type CategoryGroupUpdate = {
    name: string;
    description?: (string | null);
};

export type CategoryPublic = {
    id: string;
    ledger_id: string;
    category_group_id: string;
    name: string;
    description: (string | null);
    is_active: boolean;
    code: (string | null);
    creation_policy: ObligationCreationPolicy;
    period_generation_policy: PeriodGenerationPolicy;
    currency: (string | null);
    due_day: (number | null);
    archived_at: (string | null);
};

export type CategoryUpdate = {
    name: string;
    description?: (string | null);
    code?: (string | null);
    creation_policy: ObligationCreationPolicy;
    period_generation_policy: PeriodGenerationPolicy;
    currency?: (string | null);
    due_day?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LedgerAccessRole = 'owner' | 'editor' | 'viewer';

export type LedgerCreate = {
    name: string;
    description?: (string | null);
};

export type LedgerMemberPublic = {
    ledger_id: string;
    user_id: string;
    email: string;
    full_name: (string | null);
    role: LedgerAccessRole;
    created_at: string;
};

export type LedgerMembersPublic = {
    data: Array<LedgerMemberPublic>;
    count: number;
};

export type LedgerPublic = {
    id: string;
    owner_user_id: string;
    name: string;
    description: (string | null);
    created_at: string;
    updated_at: string;
};

export type LedgerShare = {
    user_id?: (string | null);
    email?: (string | null);
    role: LedgerAccessRole;
};

export type LedgersPublic = {
    data: Array<LedgerPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type ObligationCreationPolicy = 'manual_only' | 'auto_only' | 'hybrid';

export type PeriodGenerationPolicy = 'precreate' | 'on_demand';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CategoriesReadCategoryGroupsData = {
    includeArchived?: boolean;
    ledgerId: string;
};

export type CategoriesReadCategoryGroupsResponse = (CategoryGroupsPublic);

export type CategoriesCreateCategoryGroupData = {
    ledgerId: string;
    requestBody: CategoryGroupCreate;
};

export type CategoriesCreateCategoryGroupResponse = (CategoryGroupPublic);

export type CategoriesUpdateCategoryGroupData = {
    categoryGroupId: string;
    ledgerId: string;
    requestBody: CategoryGroupUpdate;
};

export type CategoriesUpdateCategoryGroupResponse = (CategoryGroupPublic);

export type CategoriesArchiveCategoryGroupData = {
    categoryGroupId: string;
    ledgerId: string;
};

export type CategoriesArchiveCategoryGroupResponse = (CategoryGroupPublic);

export type CategoriesReadCategoriesData = {
    categoryGroupId?: (string | null);
    includeArchived?: boolean;
    ledgerId: string;
};

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    ledgerId: string;
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    categoryId: string;
    ledgerId: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesArchiveCategoryData = {
    categoryId: string;
    ledgerId: string;
};

export type CategoriesArchiveCategoryResponse = (CategoryPublic);

export type LedgersReadLedgersResponse = (LedgersPublic);

export type LedgersCreateLedgerData = {
    requestBody: LedgerCreate;
};

export type LedgersCreateLedgerResponse = (LedgerPublic);

export type LedgersReadLedgerData = {
    ledgerId: string;
};

export type LedgersReadLedgerResponse = (LedgerPublic);

export type LedgersReadLedgerMembersData = {
    ledgerId: string;
};

export type LedgersReadLedgerMembersResponse = (LedgerMembersPublic);

export type LedgersShareLedgerData = {
    ledgerId: string;
    requestBody: LedgerShare;
};

export type LedgersShareLedgerResponse = (LedgerMemberPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);